#pragma once
#define TARGET_FPS 30
#define SCREEN_WIDTH 320
#define SCREEN_HEIGHT 200
#define VSCREEN_TILE_W 22
#define VSCREEN_TILE_H 15 
#define VSCREEN_W VSCREEN_TILE_W*TILE_SIZE
#define VSCREEN_H VSCREEN_TILE_H*TILE_SIZE
#define TILE_SIZE 16
#define WALK_SPEED 4
#define CHARACTER_SPRITE_WIDTH 32
#define CHARACTER_SPRITE_HEIGHT 32
#define CHARACTER_HITBOX_X_OFFSET 8
#define CHARACTER_HITBOX_Y_OFFSET 16
#define CHARACTER_HITBOX_WIDTH 16
#define CHARACTER_HITBOX_HEIGHT 16